//
// Generated by http://jsongen.byingtondesign.com/
//
//
package applications.haywood.torideornottoride;

public class ZipCodeWeather {
    private ZipCodeWeatherCurrently zipCodeWeatherCurrently;
    private ZipCodeWeatherFlags zipCodeWeatherFlags;
    private Number latitude;
    private Number longitude;
    private ZipCodeWeatherMinutely zipCodeWeatherMinutely;
    private Number offset;
    private String timezone;

    public ZipCodeWeatherCurrently getZipCodeWeatherCurrently() {
        return this.zipCodeWeatherCurrently;
    }

    public void setZipCodeWeatherCurrently(ZipCodeWeatherCurrently zipCodeWeatherCurrently) {
        this.zipCodeWeatherCurrently = zipCodeWeatherCurrently;
    }

    public ZipCodeWeatherFlags getZipCodeWeatherFlags() {
        return this.zipCodeWeatherFlags;
    }

    public void setZipCodeWeatherFlags(ZipCodeWeatherFlags zipCodeWeatherFlags) {
        this.zipCodeWeatherFlags = zipCodeWeatherFlags;
    }

    public Number getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Number latitude) {
        this.latitude = latitude;
    }

    public Number getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Number longitude) {
        this.longitude = longitude;
    }

    public ZipCodeWeatherMinutely getZipCodeWeatherMinutely() {
        return this.zipCodeWeatherMinutely;
    }

    public void setZipCodeWeatherMinutely(ZipCodeWeatherMinutely zipCodeWeatherMinutely) {
        this.zipCodeWeatherMinutely = zipCodeWeatherMinutely;
    }

    public Number getOffset() {
        return this.offset;
    }

    public void setOffset(Number offset) {
        this.offset = offset;
    }

    public String getTimezone() {
        return this.timezone;
    }

    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }
}
